### ISSUE TITLE
Bigmoji

### ISSUE THREAD

**Issue by aikaterna** [jcsumlin/Peribot#30]
Your bigmoji cog has been copied from Flapjack cogs without any attribution.

**Comment by jcsumlin** [comment]
Could you please link to those cogs? That code was copied from a bot know as Bobby. I'd be happy to add attribution.

**Comment by aikaterna** [comment]
https://github.com/flapjax/FlapJack-Cogs/blob/red-v3-rewrites/bigmoji/bigmoji.py

**Comment by aikaterna** [comment]
Didn't mean to close, feel free to reopen if you'd like to chat any more about it.
